 apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-snake
  name: deployment-snake
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: snake-game
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snake-game
    spec:
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"
      containers:
      - name: snake-game
        image: vamsikrishna212/snake-game:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

